### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by clem16** [lundman/FXP.One#20]
Any Idea why its failing to build?
Latest version of FreeBSD 11.2

`root@Atlas:~ # git clone https://github.com/lundman/FXP.One
Cloning into 'FXP.One'...
remote: Counting objects: 655, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 655 (delta 16), reused 16 (delta 8), pack-reused 615
Receiving objects: 100% (655/655), 872.66 KiB | 1018.00 KiB/s, done.
Resolving deltas: 100% (297/297), done.`
`root@Atlas:~/FXP.One # ./autogen.sh 
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force 
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: subdirectory lion not present
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/local/bin/autoconf-2.69 --force
autoreconf-2.69: running: /usr/local/bin/autoheader-2.69 --force
autoreconf-2.69: running: automake --add-missing --copy --force-missing
Makefile.am:1: error: required directory ./lion does not exist
clients/clomps/Makefile.am:15: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
autoreconf-2.69: automake failed with exit status: 1`

**Comment by john-at-charpa** [comment]
Yes: Makefile.am:1: error: required directory ./lion does not exist

You'll need a copy of the lion library from https://github.com/lundman/lion. Before you
run ./autogen.sh clone it into the FXP.One directory.

**Comment by cjemorton** [comment]
Thanks.
